### ISSUE TITLE
inspection_mode missing from the state of fortios_webfilter_profile

### ISSUE THREAD

**Issue by pacrutchet** [fortinetdev/terraform-provider-fortios#154]
This is the state after applying:
```HCL
resource "fortios_webfilter_profile" "webfilter" {
    dynamic_sort_subtable         = "false"
    extended_log                  = "disable"
    feature_set                   = "flow"
    https_replacemsg              = "enable"
    id                            = "ks_default_filter"
    log_all_url                   = "enable"
    name                          = "ks_default_filter"
    options                       = "block-invalid-url"
    post_action                   = "normal"
    web_antiphishing_log          = "enable"
    web_content_log               = "enable"
    web_extended_all_action_log   = "disable"
    web_filter_activex_log        = "enable"
    web_filter_applet_log         = "enable"
    web_filter_command_block_log  = "enable"
    web_filter_cookie_log         = "enable"
    web_filter_cookie_removal_log = "enable"
    web_filter_js_log             = "enable"
    web_filter_jscript_log        = "enable"
    web_filter_referer_log        = "enable"
    web_filter_unknown_log        = "enable"
    web_filter_vbs_log            = "enable"
    web_ftgd_err_log              = "enable"
    web_ftgd_quota_usage          = "enable"
    web_invalid_domain_log        = "enable"
    web_url_log                   = "enable"
    wisp                          = "disable"
    wisp_algorithm                = "primary-secondary"
    youtube_channel_status        = "disable"

    web {
        blacklist           = "disable"
        bword_table         = 0
        bword_threshold     = 10
        content_header_list = 0
        log_search          = "disable"
        urlfilter_table     = 1
        youtube_restrict    = "none"
    }
}
```

The ressource is defined as follow:
```HCL
resource "fortios_webfilter_profile" "webfilter" {
  for_each = local.webfilter.profiles
  name = each.key
  inspection_mode = each.value.inspection_mode
  options = each.value.options
  log_all_url = each.value.log_all_url

  web {
    urlfilter_table = each.value.urlfilter_id
  }
  depends_on = [
    fortios_webfilter_urlfilter.webfilter
  ]
}
```
as the consequence, it re-apply the inspection_mode as every run

PS: Thanks for this great provider!

**Comment by fgtdev-hblu** [comment]
Hi @pacrutchet Thanks for raising the issue with very clear description. Team is trying to reproduce the issue. Thanks!

**Comment by fgtdev-hblu** [comment]
Hi @pacrutchet, could you kindly provide your FortiGate firmware version:
     GUI: Dashboard->Status->System Information->Firmware
     CLI: get system status->version

**Comment by frankshen01** [comment]
@pacrutchet Thanks for the issue and such a clear description.  As far as I know, inspection_mode has been removed since FOS 6.2. The reason why the param exists here is to be compatible with FOS 6.0. As described in https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs#versioning: _The provider can cover FortiOS 6.0, 6.2, 6.4, 7.0 versions, the configuration of all parameters should be based on the relevant FortiOS version manual_ , when configuring the params, you need to follow the guidance of the relevant FortiOS version manual. For example: https://docs.fortinet.com/document/fortigate/6.4.5/cli-reference/389620/config-webfilter-profile . Or you can configure a simple setting on CLI first, then import it into terraform and modify it to match your actual usage scenarios, which may save a lot time.  Thank you!
