### ISSUE TITLE
Unable to set policyid = 0 using fortios_firewall_policy resource.

### ISSUE THREAD

**Issue by rchildress87** [fortinetdev/terraform-provider-fortios#160]
Per FortiAPI documentation, the minimum limit for a [/firewall/policy policyid](https://fndn.fortinet.net/index.php?/fortiapi/1-fortios/881/1/firewall/) value is 0:
<img width="565" alt="image" src="https://user-images.githubusercontent.com/13559499/119377615-522ba480-bc8b-11eb-8a82-74410a0cd3fb.png">

However, [resource_firewall_policy.go](https://github.com/fortinetdev/terraform-provider-fortios/blob/master/fortios/resource_firewall_policy.go#L35) appears to have the lower limit defined as 1:
```
"policyid": &schema.Schema{
	Type:         schema.TypeInt,
	ValidateFunc: validation.IntBetween(1, 2147482999),
	ForceNew:     true,
	Optional:     true,
	Computed:     true,
},
```

Further, the maximum limits do not seem to match. Is this intentional?

**Comment by frankshen01** [comment]
Hi @rchildress87, Thank you for raising the issue 👍 .  This question involves a rather complicated description, please let me try my best to describe it clearly:

In FortiAPI, policyid=0 means that the API will automatically select a policyid value and return it, and policyid is the key used to index policies. This means that if we manually configure policyid = 0 in the tf file, then when the API automatically selects a policyid and returns it to terraform, that is, policyid !=0, then every time terraform plan is executed, terraform will prompt the status is inconsistent, because the policyid in the configuration is different from the policyid returned in the terraform status file. This will cause annoyance to users. Users have to execute terraform apply every time to obtain a policyid, and then modify the policyid in the terraform configuration file according to the returned policyid in the inconsistent information, so that the terrform plan can return consistent information after the execution. This is almost unacceptable for the user's ease of use configuration, especially if a large number of policy policies are configured.

Therefore, if we want to implement automatic configuration policy by setting policyid to 0, please do not set policyid in the  tf configuration, the policyid parameter is optional. At this time, FortiAPI will return an automatically selected policyid, and terraform will update the value of policyid in the terraform state file according to the returned value. Because there is no manually entered policyid in the configuration file, there is no inconsistency between the configuration file and the state file when the terraform plan is executed. For example:

```hcl
provider "fortios" {
  hostname = "192.168.52.177"
  insecure = "true"
  token    = "GNH7r40H65GNb46kd4rG8rtrmn0fr1"
}

resource "fortios_firewall_policy" "trname1" {
    action                      = "accept"
    inspection_mode             = "flow"
    ippool                      = "disable"
    logtraffic                  = "utm"
    name                        = "d1"
    nat                         = "enable"
    status                      = "enable"

    dstaddr {
        name = "all"
    }

    dstintf {
        name = "port3"
    }

    service {
        name = "ALL"
    }

    srcaddr {
        name = "all"
    }

    srcintf {
        name = "port1"
    }
}

resource "fortios_firewall_policy" "trname2" {
    action                      = "accept"
    inspection_mode             = "flow"
    ippool                      = "disable"
    logtraffic                  = "utm"
    name                        = "d2"
    nat                         = "enable"
    status                      = "enable"

    dstaddr {
        name = "all"
    }

    dstintf {
        name = "port3"
    }

    service {
        name = "ALL"
    }

    srcaddr {
        name = "all"
    }

    srcintf {
        name = "port1"
    }
}

resource "fortios_firewall_policy" "trname3" {
    action                      = "accept"
    inspection_mode             = "flow"
    ippool                      = "disable"
    logtraffic                  = "utm"
    name                        = "d3"
    nat                         = "enable"
    status                      = "enable"

    dstaddr {
        name = "all"
    }

    dstintf {
        name = "port3"
    }

    service {
        name = "ALL"
    }

    srcaddr {
        name = "all"
    }

    srcintf {
        name = "port1"
    }
}

```

```
# terraform apply
...

# terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

fortios_firewall_policy.trname2: Refreshing state... [id=2]
fortios_firewall_policy.trname3: Refreshing state... [id=3]
fortios_firewall_policy.trname1: Refreshing state... [id=1]

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

# terraform show
# fortios_firewall_policy.trname1:
resource "fortios_firewall_policy" "trname1" {
    action                      = "accept"

    ...

    permit_any_host             = "disable"
    permit_stun_host            = "disable"
    policyid                    = 1
    profile_protocol_options    = "default"
    profile_type                = "single"

    ...

    srcintf {
        name = "port1"
    }
}

# fortios_firewall_policy.trname2:
resource "fortios_firewall_policy" "trname2" {
    action                      = "accept"
 
    ...

    permit_any_host             = "disable"
    permit_stun_host            = "disable"
    policyid                    = 2
    profile_protocol_options    = "default"
    profile_type                = "single"

    ...

    srcintf {
        name = "port1"
    }
}

# fortios_firewall_policy.trname3:
resource "fortios_firewall_policy" "trname3" {
    action                      = "accept"
    anti_replay                 = "enable"

    ...

    permit_any_host             = "disable"
    permit_stun_host            = "disable"
    policyid                    = 3
    profile_protocol_options    = "default"
    profile_type                = "single"

    ...


    srcaddr {
        name = "all"
    }

    srcintf {
        name = "port1"
    }
}
```
We can see that all policyids have been automatically created and assigned and the terraform plan also keeps the return status consistent.

As for the maximum value, this is because the repo's source code serves darwin_amd64, freebsd_386, freebsd_amd64, freebsd_arm, freebsd_arm64, linux_386, linux_amd64, linux_arm, linux_arm64, windows_386, windows_amd64...  at the same time as required by Hashicorp. For operating systems such as freebsd_386, 4294967294 exceeds the range of the maximum integer value allowed by the system, so currently we reduced the value range of the policy so that the resource can be adapted to the various operating system platforms mentioned above, and as far as possible to match the system platform that may increase in the future.

Hope this helps.  Please feel free to contact me if you need any further information. Thank you!

**Comment by rchildress87** [comment]
This all makes complete sense. I did not understand that omitting a policyid argument altogether would result in an automatically configured ID.

Thank you for the explanation about the reasoning behind the upper limit, as well.
