### ISSUE TITLE
data source fortios_system_interface ip returning incorrect syntax

### ISSUE THREAD

**Issue by ilfox** [fortinetdev/terraform-provider-fortios#166]
When querying an interface IP, according to the [documentation](https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/data-sources/fortios_system_interface#ip), instead of returning the value in the CIDR notation, a netmask is being returned. 

```
#data.fortios_system_interface.sb_infra[0]:
--
data "fortios_system_interface" "sb_infra" {
ip = "10.144.208.129 255.255.255.128"
}
```

from what I can see in the module, there isn't a conversion being done similar to the TrustIP vars

IP -> https://github.com/fortinetdev/terraform-provider-fortios/blob/master/fortios/data_source_system_interface.go#L1466
TrustIP -> https://github.com/fortinetdev/terraform-provider-fortios/blob/master/fortios/data_source_system_interface.go#L1741

Conversion function;
https://github.com/fortinetdev/terraform-provider-fortios/blob/4ed9926333833ebeb6675c6dd2b0fae8bbec9ea6/fortios/config.go#L15 

Additional info:
terraform 0.13
fortigate fortios 6.4.5

**Comment by frankshen01** [comment]
Hi @ilfox , validateConvIPMask2CIDR, this function is not intended to force the result from ipmask to CIDR, this function is mainly for maintaining state consistency of terraform plan. For example: 

For trusthost, if the user uses 1.1.1.1/24 when configuring trusthost, but because the API will return 1.1.1.1 255.255.255.0, if no conversion is done at this time, the terraform plan will display inconsistent status. So the function will convert 1.1.1.1 255.255.255.0 to 1.1.1.1/24 at this time.  If the user uses 1.1.1.1 255.255.255.0 when configuring the trusthost, since the API will return 1.1.1.1 255.255.255.0, the terraform plan will show the same status. The function will not do any conversion at this time.

As for the interface->ip you reminded, the conversion function has been added to it in the latest version. Thanks for the reminder.

In fact, in the data source, this function does not do any conversion, it will only directly return the format returned by the API. If you want to force the conversion of ip mask to CIDR, you can use the following method(included in the latest release):

```hcl

data "fortios_system_interface" trname {
  name = "port3"
}

data "fortios_ipmask_cidr" trname1 {
  ipmask = data.fortios_system_interface.trname.ip
}

output output_conv1 {
  value = data.fortios_ipmask_cidr.trname1.cidr
}


data "fortios_ipmask_cidr" trname2 {
  ipmask = "21.1.1.1 255.255.255.0"

  ipmasklist = [
    "21.1.1.1 255.255.255.0",
    "22.1.1.1 255.255.255.240",
    "23.1.1.1 255.255.255.224",
  ]
}

output output_conv2 {
  value = data.fortios_ipmask_cidr.trname2.cidr
}

output output_conv3 {
  value = data.fortios_ipmask_cidr.trname2.cidrlist
}

```
It will output:

```
# terraform apply
data.fortios_system_interface.trname: Refreshing state...
data.fortios_ipmask_cidr.trname2: Refreshing state...
data.fortios_ipmask_cidr.trname1: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

output_conv1 = 1.1.1.1/24
output_conv2 = 21.1.1.1/24
output_conv3 = [
  "21.1.1.1/24",
  "22.1.1.1/28",
  "23.1.1.1/27",
]

```
If you have any questions, please do not hesitate to contact me. Thank you!

**Comment by poroping** [comment]
Sorry for the hijack but I've been wondering if the provider should implement this in every situation of IP/Mask.

For our IaC pipeline we are utilising CIDR format everywhere as the majority of the other vendors we are utilising Terraform for use this format. At the moment I have to do a bunch of data mutation to convert to IP netmask. It would be much easier if the provider could handle this.

Handling this within the provider is actually HashiCorp's preferred method, see: https://github.com/hashicorp/terraform/issues/23905
