### ISSUE TITLE
unable to create a new vdom using terraform

### ISSUE THREAD

**Issue by jungekim** [fortinetdev/terraform-provider-fortios#254]
I am using as follows;
 - fortios: v7.0.3
 - terraform: fortinetdev/fortios v1.16.0

module.create_new_vdom.fortios_system_vdom.vdom_list["test-vdom"]: Creating...
╷
│ Error: Error creating SystemVdom resource: Forbidden - Request is missing CSRF token or administrator is missing access profile permissions (403)
│ 
│   with module.create_new_vdom.fortios_system_vdom.vdom_list["test-vdom"],
│   on ../../../modules/fortios/vdom/main.tf line 3, in resource "fortios_system_vdom" "vdom_list":
│    3: resource "fortios_system_vdom" "vdom_list" {

**Comment by MaxxLiu22** [comment]
Hi @jungekim ,

Thank you for raising this issue. This error usually happens if you use a wrong token, or don't give an appropriate permission profile to the API user, for the former reason, you could run ``execute api-user generate-key {{api user name}}`` under global vdom to generate a new token, for the latter reason, you could run following cmd to check if you give an appropriate permission to the api user, here I give the api user full permission by setting accprofile to “super_admin”. If this still doesn't fix your problem, please let me know.
```
FGVMULTM22003786 (global) # config system api-user 

FGVMULTM22003786 (api-user) # edit api 

FGVMULTM22003786 (api) # show
config system api-user
    edit "api"
        set api-key ENC SH23Pp9+QRwI/BL67FYC7s/Ai0qflop6S96pMCSO6uB2jCvlI5U1twLBZjJJHg=
        set accprofile "super_admin"
        set vdom "testvdom"
    next
end
```
Thanks,
Maxx

**Comment by jungekim** [comment]
after adding the permission, "set accprofile "super_admin"", i have solved the problem!!!
Thank you so much!!
