### ISSUE TITLE
fortios_networking_route_static dialup VPN trying to update in-place

### ISSUE THREAD

**Issue by zippanto** [fortinetdev/terraform-provider-fortios#282]
Hi,

We are managing a route pointing at a dialup IPSec interface. When connecting to a firewall running 7.0 terraform is trying to update the route in-place. Please see below.

```
  # fortios_networking_route_static.route will be updated in-place
  ~ resource "fortios_networking_route_static" "route" {
      ~ gateway   = "10.0.0.1" -> "0.0.0.0"
        id        = "10"
        # (8 unchanged attributes hidden)
    }
```

Please note the gateway address shown as "10.0.0.1". As far as we can tell this doesn't exist anywhere. Please see below for the configuration present on the firewall.

```
config router static
    edit 10
        set dst 192.168.0.0 255.255.0.0
        set distance 25
        set device "AA"
        set comment "Managed by Terraform"
    next
end
```

Running the same plan on a firewall running 6.4 everything is working as expected, there is no change proposed by terraform.

Please advise.

Thanks

**Comment by MaxxLiu22** [comment]
Hi @zippanto ,

Thank you for raising this question, ``fortios_networking_route_static`` is an old version resource and that will be deprecated, you are welcome to use [fortios_router_static](https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/data-sources/fortios_router_static) instead, in this new resource, you don't have to define ``gateway`` since a tunnel has a fixed gateway defined. Let me know if that doesn't work.

```
resource "fortios_router_static" "trname" {
  device              = "ipsec_tunnel"
  distance            = 10
  dst                 = "2.0.0.0 255.240.0.0"
}
```

Thanks,
Maxx
