### ISSUE TITLE
Critical Error: Using TF provider 1.21.0 for Fortigate 200F (ver 7.2.8) breaks down all BGP sessions

### ISSUE THREAD

**Issue by Vokunne** [fortinetdev/terraform-provider-fortios#337]
Hi everyone,

Today I tried to update TF provider version from 1.20.0 to 1.21.0 and got a situation when all BGP sessions from Fortigate HA cluster dropped down.

Some tech details:

Terraform 1.9.5
Terraform Fortios provider version: 1.21.0
Fortigate FGCP HA cluster (nodes are sync): current version 7.2.8

What happened:

During plan stage (with new provider 1.21.0) there was a small but significant changing in "fortios_router_bgp" resource. It looked like that:

# module.bgp.fortios_router_bgp.bgp_conf will be updated in-place
  ~ resource "fortios_router_bgp" "bgp_conf" {
      - as_string                          = "64000" -> null
        id                                 = "RouterBgp"
        # (54 unchanged attributes hidden)
        # (8 unchanged blocks hidden)
    }

Unfortunately, I didn't pay attention to it 'cause there were a lot of changes in different resources. It led that after applying a terraform plan, all BGP session broke down.

To fix the issue I just restored "as_string" value as it was before and BGP sessions got up. 
More than that, I've compared "fortios_router_bgp" resource for TF backend ver. 1.20.0 and 1.21.0 (different HA clusters but the same version 7.2.8) and the main difference was only in this value:

TF backend for 1.20.0: (BGP sessions are OK)
"resources": [
    {
      "module": "module.bgp",
      "mode": "managed",
      "type": "fortios_router_bgp",
// output omitted
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
// output omitted
         "as": 64001,                  <------------- Configured BGP ASN
         "as_string": "64001",   <------------- Inserted BGP ASN by default TF provider behavior 

TF backend for 1.21.0: (BGP sessions are down after apply)
"resources": [
    {
      "module": "module.bgp",
      "mode": "managed",
      "type": "fortios_router_bgp",
// output omitted
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
// output omitted
         "as": 64000,                  <------------- Configured BGP ASN
         "as_string": "",              <------------- Deleted BGP ASN by default TF provider behavior 

I can't recommend to roll back this TF version highly enough. I guess that support FortiOS version 7.6.0 in the latest version of TF provider the main cause of braking down BGP sessions.

**Comment by MaxxLiu22** [comment]
Hi @Vokunne ,

I sincerely apologize for the inconvenience caused by the upgrade of the FOS provider, which has led to unexpected issues on your end. The root of the issue stems from the fact that, starting with version 1.21.0, the Terraform FOS provider began fully managing all arguments. This means that if an argument is not explicitly defined in your Terraform configuration and is capable of being unset to empty or assigned a default value, Terraform will automatically set it to null, which appears to be what you have encountered.

In earlier versions of the provider, we would only update the configurations you defined in your .tf file, leaving any undefined arguments unchanged. However, this approach prevented some customers from being able to remove certain configurations when necessary.

Additionally, the data type for ``as`` changed from an integer to a string as of FOS 7.2.1. The value "as": 64000 may have been inherited from an older configuration or set earlier, though it does not impact FOS 7.2.8. The as_string value should now reflect your current FOS status.

Once again, I sincerely regret any difficulties this upgrade has caused, and I truly appreciate your understanding. Please let me know if there is anything further I can assist you with.

Thanks,
Maxx

**Comment by Vokunne** [comment]
Hi @MaxxLiu22 ,

Thank you very much indeed for the clear explanation of the root cause. This one was really helpful and I will definitely follow your advice how to align my terraform configuration to the new provider's requirements.

Best,
Roman
