### ISSUE TITLE
Argument "psksecret" for resources fortios_vpnipsec_phase1 and fortios_vpnipsec_phase1interface should be marked as sensitive

### ISSUE THREAD

**Issue by crawfs** [fortinetdev/terraform-provider-fortios#86]
Terraform allows providers to control which resources are considered sensitive to avoid them being leaked in plans and output variables. This is one such argument that needs to be marked as sensitive in order to avoid unintentionally leaking the IPSec pre-shared key.

**Comment by frankshen01** [comment]
Hi @crawfs,  we think this is a good suggestion and will evaluate it later. Thanks!

**Comment by crawfs** [comment]
Thanks @frankshen01 I've identified a bunch more that should be considered sensitive, should I create new issues for each of them?

**Comment by frankshen01** [comment]
hi @crawfs, thanks for your suggestions for improvement, they are very valuable.  I think we can continue to discuss this issue here, so as to reduce your workload and we can focus on the issue also. I wonder if my suggestion is appropriate?  

We are looking forward to seeing a bunch more contents you selected! BTW: We have listed a draft for these more than 100 attributes to be set to sensitive, and will support them in the next FOS release after optimization and testing:   https://github.com/fortinetdev/terraform-provider-fortios/blob/ti-slash/tmpinfoexchange (it will be deleted later). Any your suggestions and improvements are welcome! Thanks!

**Comment by crawfs** [comment]
Ah neat, yeah looks like that link contains everything I noticed needed to be sensitive. Good to see.

**Comment by frankshen01** [comment]
Supported and released, please see the latest version(v1.6.2): https://registry.terraform.io/providers/fortinetdev/fortios/latest, Thanks!
